name: Initialize gh-pages branch

on:
  push:
    branches:
      - main

jobs:
  initialize-gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create gh-pages branch
        run: |
          git config --global user.email "georgezyryanov@gmail.com"
          git config --global user.name "George Zyryanov"
          git checkout --orphan gh-pages
          git rm -rf .
          echo "# Test Reports" > index.html
          git add index.html
          git commit -m "Initialize gh-pages branch"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 